apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appwrite

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml.example
  - deployment.yaml
  - service.yaml

commonLabels:
  app: appwrite-executor
